# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  release:
    types: [created]

jobs:
  check:
    outputs:
      status: ${{ steps.check_pr_labels.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run a one-line script
        run: |
          echo "Release result: ${{ job.status }}\n${{ github.repository }}: ${{ github.ref_name }}\nRelease info: ${{ github.event.release.name }}, ${{ github.event.release }} ${{ github.event.payload }}"

      - name: Run a multi-line script
        if: ${{startsWith(github.event.release.name, "qwe")}}

      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result}}"

  deploy:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: See result
        run: |
          echo needs.check.outputs.status
