name: Deploy brg to cloudfront

on:
    push:
        # 이 부분에 원하는 브랜치 명을 입력하시면 해당 브랜치로 푸쉬 시, staging-brg3.break.co.kr 이 업데이트 됩니다.
        branches:
            - 'BRG-838-프론트-주문-상세내역에-단계-추가'

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '15.x'
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: '3.x'
            - name: Install AWS CLI
              run: pip3 install awscli --upgrade --user
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CLOUDFRONT_S3 }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CLOUDFRONT_S3 }}
                  aws-region: ${{ secrets.AWS_REGION }}
                  mask-aws-account-id: true
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: CI= npm run build:staging
            - name: Push Contents to S3
              run: aws s3 sync ./build s3://${{ secrets.STAGING3_S3_BUCKET_NAME }}
            - name: Invalidate CloudFront Cache
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING3_CDN_DISTRIBUTION_ID }} --paths "/*"
